name = "ITensorNHDMRG"
uuid = "8eead381-b44f-4c25-a327-91918c5e5257"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.0"

[deps]
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
VectorInterface = "409d34a3-91d5-4945-b6ec-7529ddf182d8"

[compat]
Aqua = "0.8.9"
ITensorMPS = "0.3.19"
ITensors = "0.9.5"
KrylovKit = "0.10"
Printf = "1.11.0"
SafeTestsets = "0.1"
Suppressor = "0.2"
Test = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "Suppressor", "SafeTestsets"]
